from typing import Protocol

from scheduler.request import InferenceRequest


class LocalRequestScheduler(Protocol):
    async def submit(self, request: InferenceRequest) -> None: ...
    def cancel(self, request: InferenceRequest, reason: str) -> None: ...
    def queue_depth(self) -> int: ...
    def close(self) -> None: ...
