from collections.abc import Sequence
from typing import Protocol

from serving_platform.domain import ModelDefinition, WorkerState


class ModelRegistry(Protocol):
    def get(self, model_id: str) -> ModelDefinition | None: ...
    def list(self) -> Sequence[ModelDefinition]: ...


class WorkerRegistry(Protocol):
    def get(self, worker_id: str) -> WorkerState | None: ...
    def list(self) -> Sequence[WorkerState]: ...
    def register(self, worker: WorkerState) -> None: ...
