from collections.abc import Sequence
from typing import Protocol

from serving_platform.domain import ModelDefinition, WorkerState


class ModelRegistry(Protocol):
    def get(self, model_id: str) -> ModelDefinition | None: ...
    def list(self) -> Sequence[ModelDefinition]: ...
    def register(self, model: ModelDefinition) -> None: ...


class WorkerRegistry(Protocol):
    def get(self, worker_id: str) -> WorkerState | None: ...
    def list(self) -> Sequence[WorkerState]: ...
    def register(self, worker: WorkerState) -> None: ...
    def heartbeat(self, worker: WorkerState) -> None: ...
    def unregister(self, worker_id: str) -> None: ...
    def expire_stale(self) -> Sequence[str]: ...
